/**
 * Reading the CLI's slash-command envelopes.
 *
 * The fixtures here are verbatim from stored transcripts — including the
 * inconsistent tag order and the ANSI in the output — because the SDK types do
 * not describe this payload at all, so the only specification is what the CLI
 * actually writes.
 */

import { describe, expect, it } from 'vitest';

import { parseCommandEnvelope, stripAnsi } from '../localCommand.js';

/** ESC and BEL, spelled out, so the fixtures read as what arrives on the wire. */
const ESC = '\u001B';
const BEL = '\u0007';

describe('parseCommandEnvelope', () => {
  it('reads a name-first invocation with empty args', () => {
    // Verbatim, indentation and all: `/effort` as the CLI wrote it.
    const envelope = parseCommandEnvelope(
      '<command-name>/effort</command-name>\n' +
        '            <command-message>effort</command-message>\n' +
        '            <command-args></command-args>',
    );
    // Present-and-empty args are absence, not an empty argument.
    expect(envelope).toEqual({ kind: 'invocation', name: 'effort' });
  });

  it('reads a message-first invocation, because the order is not stable', () => {
    const envelope = parseCommandEnvelope(
      '<command-message>mattpocock-skills:to-tickets</command-message>\n' +
        '<command-name>/mattpocock-skills:to-tickets</command-name>\n' +
        '<command-args>convert the remaining tickets</command-args>',
    );
    expect(envelope).toEqual({
      kind: 'invocation',
      // The namespace is part of what the user typed and is kept.
      name: 'mattpocock-skills:to-tickets',
      args: 'convert the remaining tickets',
    });
  });

  it('keeps multi-line arguments whole', () => {
    // A plugin command takes the user's whole request as one argument, so a
    // greedy or line-oriented match would truncate it.
    const envelope = parseCommandEnvelope(
      '<command-name>/ask</command-name><command-args>first line\nsecond line</command-args>',
    );
    expect(envelope).toEqual({ kind: 'invocation', name: 'ask', args: 'first line\nsecond line' });
  });

  it('falls back to the label when only the message tag is present', () => {
    expect(parseCommandEnvelope('<command-message>implement</command-message>')).toEqual({
      kind: 'invocation',
      name: 'implement',
    });
  });

  it('reads stdout and strips the terminal codes out of it', () => {
    const envelope = parseCommandEnvelope(
      `<local-command-stdout>Set model to ${ESC}[1mFable 5${ESC}[22m and saved as your default</local-command-stdout>`,
    );
    expect(envelope).toEqual({
      kind: 'output',
      text: 'Set model to Fable 5 and saved as your default',
      failed: false,
    });
  });

  it('marks stderr as failed', () => {
    expect(parseCommandEnvelope('<local-command-stderr>no such command</local-command-stderr>')).toEqual(
      { kind: 'output', text: 'no such command', failed: true },
    );
  });

  it('recognises the caveat, which is addressed to the model', () => {
    expect(
      parseCommandEnvelope(
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages…</local-command-caveat>',
      ),
    ).toEqual({ kind: 'caveat' });
  });

  it('leaves ordinary prose alone', () => {
    expect(parseCommandEnvelope('can we ship this today?')).toBeNull();
    expect(parseCommandEnvelope('')).toBeNull();
    // Prose that merely *contains* markup is still prose: an envelope is the
    // whole message, and a user quoting one has not run a command.
    expect(parseCommandEnvelope('why does <command-name>/x</command-name> render badly?')).toBeNull();
  });

  it('declines a nameless invocation rather than drawing an anonymous chip', () => {
    expect(parseCommandEnvelope('<command-name></command-name>')).toBeNull();
    expect(parseCommandEnvelope('<command-name>/</command-name>')).toBeNull();
  });

  it('does not mistake an unrelated tag for an envelope', () => {
    expect(parseCommandEnvelope('<thinking>hmm</thinking>')).toBeNull();
  });
});

describe('stripAnsi', () => {
  it('removes colour and bold without touching the text', () => {
    expect(stripAnsi(`${ESC}[31mred${ESC}[0m and ${ESC}[1mbold${ESC}[22m`)).toBe('red and bold');
  });

  it('removes an OSC hyperlink, terminator and all', () => {
    // OSC is stripped before CSI: its payload can contain what looks like the
    // start of a CSI sequence, and cutting that first would strand the rest.
    expect(stripAnsi(`${ESC}]8;;https://example.com${ESC}\\link${ESC}]8;;${ESC}\\`)).toBe('link');
    expect(stripAnsi(`${ESC}]0;a title${BEL}after`)).toBe('after');
  });

  it('leaves text with no escapes untouched', () => {
    expect(stripAnsi('plain [1m text')).toBe('plain [1m text');
  });
});
