/**
 * Sharing one `~/.claude` across every profile — as a script, not as an action.
 * ============================================================================
 *
 * Artemis gives each profile its own `CLAUDE_CONFIG_DIR`, and that one variable
 * buys isolated auth *and* isolated everything-else. The isolation is the point
 * for the credential and an irritation for the rest: a skill written once has to
 * be written again per account, and history splits four ways for no reason the
 * user asked for.
 *
 * This module writes the shell that undoes the second half without touching the
 * first — symlinks from each profile's directory to the matching entry under
 * the user's own `~/.claude` — and reads the main process's report of what that
 * shell actually did.
 *
 * ---------------------------------------------------------------------------
 * WHY A SCRIPT AND NOT A BUTTON
 * ---------------------------------------------------------------------------
 *
 * Artemis does not run this. It generates text, the user reads it, and the user
 * runs it in their own terminal.
 *
 * That is a deliberate refusal rather than an unfinished feature. The operation
 * moves directories that hold months of transcripts, across accounts, on paths
 * this app got from a JSON file a user can edit. A button would make that a
 * single click with no diff to read and no record of what happened; a script is
 * reviewable before it runs, greppable after it ran, and re-runnable outside
 * Artemis when the app is not the thing that is broken. The generator is pure
 * for the same reason — it is the part worth testing, and it can be tested
 * without a filesystem.
 *
 * The cost of that refusal is that the app has no idea whether the user ran
 * anything, which is what the second half of this module is about: the reading
 * comes back over `sharedConfig.status`, and everything below
 * {@link entryGap} turns nine states per profile into the two or three sentences
 * a pane can show. All of it pure, for the same reason the generator is.
 *
 * ---------------------------------------------------------------------------
 * WHERE THE VOCABULARY LIVES
 * ---------------------------------------------------------------------------
 *
 * {@link SHARED_DIRECTORIES}, {@link SHARED_FILES}, {@link BACKUP_SUFFIX} and
 * {@link sharedConfigDirs} moved to `@rx-artemis/protocol` when the status
 * display was added, and are re-exported here so that this module stays the one
 * import for anything to do with the arrangement. They had to move: the main
 * process `lstat`s exactly these names, and a second copy of the list is a
 * script that links a directory the pane will never mention.
 */

import {
  BACKUP_SUFFIX,
  SHARED_DIRECTORIES,
  SHARED_FILES,
  type SharedConfigDirStatus,
  type SharedConfigEntry,
  type SharedConfigStatus,
} from '@rx-artemis/protocol';

export {
  BACKUP_SUFFIX,
  SHARED_DIRECTORIES,
  SHARED_ENTRIES,
  SHARED_FILES,
  sharedConfigDirs,
} from '@rx-artemis/protocol';

/** Which script to generate. */
export type SharedConfigMode = 'share' | 'restore';

/**
 * Quote one value for `/bin/sh`.
 *
 * Single quotes and the `'\''` dance, because the inputs are profile
 * directories and the default on macOS lives under `~/Library/Application
 * Support` — a path with a space in it, in the one position where losing the
 * split turns `mv` into a two-argument command aimed at the wrong place.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * Build the script.
 *
 * `/bin/sh`, not bash: the only bash-isms this needs are conveniences, and a
 * script the user is about to paste into whatever shell they happen to run
 * should not fail on the shebang. `set -eu` rather than `pipefail` for the same
 * reason — there are no pipes here, and `pipefail` is not POSIX.
 *
 * The root is written as `$HOME/.claude` and left for the shell to expand. The
 * renderer does not know the home directory, and asking the main process for it
 * would add an IPC channel to interpolate a string the shell already has.
 */
export function buildSharedConfigScript(dirs: readonly string[], mode: SharedConfigMode): string {
  return mode === 'share' ? shareScript(dirs) : restoreScript(dirs);
}

/** `profile 'a'` lines, or a comment where the list is empty. */
function calls(dirs: readonly string[], fn: string): string {
  if (dirs.length === 0) return '# No Claude profiles to cover.';
  return dirs.map((dir) => `${fn} ${shellQuote(dir)}`).join('\n');
}

function shareScript(dirs: readonly string[]): string {
  return `#!/bin/sh
#
# Shared Claude config — generated by Artemis.
# ==========================================================================
#
# Points the shareable parts of each Artemis Claude profile at your own
# ~/.claude, so commands, skills, plugins, plans and history are the same
# whichever account a run uses.
#
# NOT touched: .claude.json, settings.json, sessions/ and the stored
# credential. Those stay per profile — they are what make the accounts
# separate accounts, and linking them signs every profile into whichever one
# logged in last.
#
# Nothing is deleted. Anything already in a profile is renamed to
# <name>${BACKUP_SUFFIX} first, and the "stop sharing" script puts it back.
#
# Re-running this is safe: a link that already points at the root is left as
# it is, and no second backup is made.
#
# Quit Artemis before running it, so nothing is writing to these paths.

set -eu

ROOT="$HOME/.claude"
SUFFIX="${BACKUP_SUFFIX}"

SHARED_DIRS="${SHARED_DIRECTORIES.join(' ')}"
SHARED_FILES="${SHARED_FILES.join(' ')}"

# Move whatever is at $1 out of the way, then link it to $2.
link_one() {
  target="$1"
  source="$2"

  if [ -L "$target" ] && [ "$(readlink "$target")" = "$source" ]; then
    printf '  keep  %s\\n' "$target"
    return 0
  fi

  if [ -e "$target" ] || [ -L "$target" ]; then
    backup="$target$SUFFIX"
    n=2
    while [ -e "$backup" ] || [ -L "$backup" ]; do
      backup="$target$SUFFIX.$n"
      n=$((n + 1))
    done
    mv "$target" "$backup"
    printf '  move  %s -> %s\\n' "$target" "$backup"
  fi

  ln -s "$source" "$target"
  printf '  link  %s\\n' "$target"
}

profile() {
  dir="$1"

  # Linking the root to itself would replace every shared folder with a link
  # to the backup it was just renamed into. A profile is allowed to name
  # ~/.claude directly, so this is a real case and not a defensive check.
  if [ "$dir" = "$ROOT" ]; then
    printf '%s\\n  skip  this is ~/.claude itself\\n' "$dir"
    return 0
  fi
  if [ ! -d "$dir" ]; then
    printf '%s\\n  skip  no such directory\\n' "$dir"
    return 0
  fi

  printf '%s\\n' "$dir"

  for name in $SHARED_DIRS; do
    mkdir -p "$ROOT/$name"
    link_one "$dir/$name" "$ROOT/$name"
  done

  for name in $SHARED_FILES; do
    if [ ! -e "$ROOT/$name" ]; then
      printf '  skip  %s (no %s to share)\\n' "$name" "$ROOT/$name"
      continue
    fi
    link_one "$dir/$name" "$ROOT/$name"
  done
}

mkdir -p "$ROOT"

${calls(dirs, 'profile')}

printf '\\nDone. Start Artemis again to pick up the new layout.\\n'
`;
}

function restoreScript(dirs: readonly string[]): string {
  return `#!/bin/sh
#
# Stop sharing the Claude config — generated by Artemis.
# ==========================================================================
#
# Undoes the sharing script: removes the links it made and moves each
# <name>${BACKUP_SUFFIX} back to where it came from.
#
# Conservative in both directions. A link is removed only when it still
# points at the matching path under ~/.claude — anything else at that name is
# something you put there since, and is left alone with a note. A backup is
# restored only onto a name that is now free, so nothing overwrites anything.
#
# Files created inside a shared folder while sharing was on stay in ~/.claude.
# They were written to the root, and this script does not try to guess which
# profile they belonged to.
#
# Quit Artemis before running it.

set -eu

ROOT="$HOME/.claude"
SUFFIX="${BACKUP_SUFFIX}"

SHARED_DIRS="${SHARED_DIRECTORIES.join(' ')}"
SHARED_FILES="${SHARED_FILES.join(' ')}"

restore_one() {
  target="$1"
  source="$2"

  if [ -L "$target" ] && [ "$(readlink "$target")" = "$source" ]; then
    rm "$target"
    printf '  unlink   %s\\n' "$target"
  elif [ -e "$target" ] || [ -L "$target" ]; then
    printf '  leave    %s (not the link this script made)\\n' "$target"
    return 0
  fi

  # Only the un-numbered backup: it is the original. A "$SUFFIX.2" exists only
  # because the name was occupied again after sharing was already on, and
  # guessing which of the two the user wants back is not this script's call.
  backup="$target$SUFFIX"
  if [ ! -e "$backup" ] && [ ! -L "$backup" ]; then
    return 0
  fi
  mv "$backup" "$target"
  printf '  restore  %s\\n' "$target"
}

profile() {
  dir="$1"

  if [ "$dir" = "$ROOT" ]; then
    printf '%s\\n  skip     this is ~/.claude itself\\n' "$dir"
    return 0
  fi
  if [ ! -d "$dir" ]; then
    printf '%s\\n  skip     no such directory\\n' "$dir"
    return 0
  fi

  printf '%s\\n' "$dir"

  for name in $SHARED_DIRS $SHARED_FILES; do
    restore_one "$dir/$name" "$ROOT/$name"
  done
}

${calls(dirs, 'profile')}

printf '\\nDone. Start Artemis again to pick up the new layout.\\n'
`;
}

/* -------------------------------------------------------------------------- */
/* Reading the status                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Is this entry work the share script still has to do?
 *
 * `linked` never is. Everything else is, with one exception that matters: a
 * *file* the root does not have is one the share script deliberately skips
 * (`skip  CLAUDE.md (no …)`), so a profile without it is correctly arranged and
 * counting it as a gap would leave a perfectly-run share reading as incomplete
 * forever. A *directory* the root lacks is not the same case — the script
 * `mkdir -p`s it and links it — so that one stays a gap.
 *
 * `foreign` counts as a gap. The share script would move it aside and link over
 * it, which is a thing that will happen and therefore a thing to show.
 */
export function entryGap(entry: SharedConfigEntry, rootMissing: readonly string[]): boolean {
  if (entry.state === 'linked') return false;
  if (entry.state !== 'missing') return true;
  return !(SHARED_FILES.includes(entry.name) && rootMissing.includes(entry.name));
}

/** How one profile directory reads, reduced to what a single line can say. */
export interface SharedConfigDirSummary {
  readonly dir: string;
  /**
   * What the pane says about this directory as a whole.
   *
   *  - `shared`   — every entry that could be linked is linked.
   *  - `partial`  — some are, some are not. The row the whole display exists for.
   *  - `unshared` — none are.
   *  - `root`     — this directory *is* `~/.claude`; both scripts skip it.
   *  - `absent`   — the directory is not there.
   */
  readonly state: 'shared' | 'partial' | 'unshared' | 'root' | 'absent';
  /** How many entries are symlinked to the root right now. */
  readonly linked: number;
  /** Names the share script would still act on, in script order. */
  readonly gaps: readonly string[];
  /** Names with a `…{@link BACKUP_SUFFIX}` sitting alongside them. */
  readonly backups: readonly string[];
}

/**
 * Reduce one directory's entries to a row.
 *
 * `shared` requires that there be at least one link, not merely no gaps: a
 * directory where the root had nothing to offer would otherwise report as fully
 * shared on the strength of entries nobody could have linked.
 */
export function summarizeDir(
  status: SharedConfigDirStatus,
  rootMissing: readonly string[],
): SharedConfigDirSummary {
  if (status.state !== 'checked') {
    return { dir: status.dir, state: status.state, linked: 0, gaps: [], backups: [] };
  }

  const linked = status.entries.filter((entry) => entry.state === 'linked').length;
  const gaps = status.entries
    .filter((entry) => entryGap(entry, rootMissing))
    .map((entry) => entry.name);
  const backups = status.entries
    .filter((entry) => entry.backup === true)
    .map((entry) => entry.name);

  const state = gaps.length === 0 && linked > 0 ? 'shared' : linked > 0 ? 'partial' : 'unshared';

  return { dir: status.dir, state, linked, gaps, backups };
}

/** Every directory's row, in the order the reading listed them. */
export function summarizeStatus(status: SharedConfigStatus): readonly SharedConfigDirSummary[] {
  return status.dirs.map((dir) => summarizeDir(dir, status.rootMissing));
}

/**
 * The directories one script still has work to do in.
 *
 * This is what the pane offers as the narrow script — the one that covers a
 * fifth account added after the first four were linked, without walking back
 * over the four. Both scripts are safe to re-run over everything, so this is not
 * a correctness fix; what it buys is a script whose text names only the
 * directories that are actually going to change, which is a shorter thing to
 * read before running it and a smaller blast radius if the reading is wrong.
 *
 * `root` and `absent` are never included, in either direction. Both scripts skip
 * them by name, so a script generated for them would print `skip` and do
 * nothing — offering it would imply Artemis could fix a directory that is not
 * there.
 */
export function dirsNeedingWork(
  status: SharedConfigStatus,
  mode: SharedConfigMode,
): readonly string[] {
  return summarizeStatus(status)
    .filter((summary) => {
      if (summary.state === 'root' || summary.state === 'absent') return false;
      // Sharing: anywhere with an entry still to link. Undoing: anywhere that
      // still has one of this arrangement's links, or a backup waiting to come
      // back — a directory the undo script would print nothing for is one there
      // is nothing left to undo in.
      return mode === 'share'
        ? summary.gaps.length > 0
        : summary.linked > 0 || summary.backups.length > 0;
    })
    .map((summary) => summary.dir);
}

/**
 * Does the disk disagree with what the switch says?
 *
 * The question the whole display exists to answer, and it is asked in both
 * directions because both are silent failures:
 *
 *  - switch on, not everything linked — the user flipped it, read the script and
 *    closed the terminal; or the script ran before the newest profile existed.
 *  - switch off, links still there — prefs were reset, or a new install met an
 *    old disk, or the script was run by hand. The pane claims isolation the
 *    accounts do not have.
 *
 * `false` when there is nothing to compare, because "you asked for sharing and
 * there are no profiles" is already said by the empty state, and saying it twice
 * in different words reads as two problems.
 */
export function statusDisagrees(status: SharedConfigStatus, intended: boolean): boolean {
  const rows = summarizeStatus(status).filter(
    (summary) => summary.state !== 'root' && summary.state !== 'absent',
  );
  if (rows.length === 0) return false;
  return intended
    ? rows.some((summary) => summary.state !== 'shared')
    : rows.some((summary) => summary.linked > 0);
}

/**
 * Is there any sign on disk that this arrangement was ever set up?
 *
 * What decides whether a user who has never touched the switch is shown a status
 * block at all. Nine `missing` entries per profile is the ordinary state of a
 * machine that never wanted this, and reporting it would turn a feature nobody
 * enabled into a paragraph of nothing-is-wrong on the Advanced pane. A link or a
 * leftover backup is different: something happened here, and the switch says it
 * did not.
 */
export function statusHasLinks(status: SharedConfigStatus): boolean {
  return status.dirs.some((dir) =>
    dir.entries.some((entry) => entry.state === 'linked' || entry.backup === true),
  );
}
