/**
 * Every Artemis colour class names a token that exists.
 *
 * Tailwind generates a utility only when the token behind it is declared. A
 * class naming a token that is not — `bg-surface`, say — compiles to nothing at
 * all: no error, no warning, no rule in the stylesheet. The element simply has
 * no fill, and it looks like a design decision.
 *
 * That is not hypothetical. `BrowserPane` styled its address bar `bg-surface`
 * for as long as the file has existed. There is no `--color-surface`, so the
 * field had no background, and nothing anywhere reported it — the built
 * stylesheet contained zero occurrences of the class while `bg-panel` had six.
 * A build that fails loudly would have caught it on the first run; a build that
 * silently drops the rule needs this.
 *
 * ## Scope
 *
 * Only Artemis's own physical tokens are checked — the ones declared in
 * `index.css` under a name this repo chose. Tailwind's built-in scales
 * (`bg-white`, `text-red-500`) and shadcn's semantic names (`bg-popover`,
 * `text-muted-foreground`) are deliberately out: they are generated by
 * machinery this test does not own, and asserting against them would mean
 * re-implementing Tailwind's resolver to find out what it already knows.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CSS = readFileSync(join(ROOT, 'index.css'), 'utf8');

/**
 * The physical token names, read from the `@theme inline` block that turns them
 * into utilities. Parsed rather than listed, so a token added tomorrow is
 * checked tomorrow without anyone remembering to come here.
 */
function declaredTokens(): Set<string> {
  const names = new Set<string>();
  for (const m of CSS.matchAll(/--color-([a-z0-9-]+):/g)) names.add(m[1]!);
  return names;
}

/**
 * The Artemis names, as opposed to the shadcn ones. Both live in the same
 * `@theme inline` block; these are the ones the file's own header calls
 * "physical" — what the colour *is* rather than what it is *for*.
 */
const ARTEMIS = /^(abyss|panel|raised|float|inset|line|line-strong|ink|ink-muted|ink-faint|beam|beam-dim|beam-ink|cyan|sage|mint|amber|signal|signal-ink)$/;

/**
 * The prefixes whose value is *always* a colour.
 *
 * `text-` and `shadow-` are deliberately absent. They are overloaded — `text-xs`
 * is a size, `text-left` an alignment, `text-balance` a wrap mode, `shadow-none`
 * a shadow — and including them meant the first draft of this test flagged
 * thirty-one files for `text-xs`. A check that cries wolf on every file is a
 * check that gets deleted, so it covers the prefixes it can judge exactly and
 * says so rather than guessing at the rest.
 */
const USE = /\b(?:bg|border|ring|fill|stroke|caret|divide|outline)-([a-z][a-z0-9-]*)/g;

/**
 * Utilities that share a prefix with a colour one but set something else:
 * `bg-clip-padding`, `bg-blend-color`, `bg-gradient-to-b`, `stroke-dasharray`.
 * Matched on their first segment, since the rest varies.
 */
const COMPOUND = /^(blend|clip|gradient|origin|dasharray|dashoffset|linecap|linejoin|radius|width|opacity|spacing|collapse|image|position|size|attachment|repeat)\b/;

/**
 * Strip the parts of a class that are not the colour, and return what is.
 *
 * `ring-offset-abyss` is an offset in `--color-abyss`; `border-t-transparent`
 * is a top border in transparent. Both would otherwise be read as tokens named
 * `offset-abyss` and `t-transparent`, which is how the first version of this
 * test flagged its own fix.
 */
function colourPart(value: string): string | null {
  let v = value;
  if (v.startsWith('offset-')) v = v.slice('offset-'.length);
  // A single-letter side: border-t-, border-x-, divide-y- and friends.
  v = v.replace(/^[lrtbxyse]-/, '');
  if (COMPOUND.test(v)) return null;
  return v;
}

/**
 * The non-colour values those prefixes legitimately take. Bounded and short,
 * which is the point of dropping the overloaded prefixes above.
 */
const NOT_A_COLOUR = new Set([
  'b', 't', 'l', 'r', 'x', 'y', 's', 'e',
  'solid', 'dashed', 'dotted', 'double', 'hidden', 'none', 'separate', 'collapse',
  'transparent', 'current', 'inherit', 'auto', 'clip', 'fixed', 'local', 'scroll',
  'contain', 'cover', 'center', 'top', 'bottom', 'left', 'right', 'repeat',
  'no', 'origin', 'linear', 'radial', 'conic', 'offset', 'inset', 'reveal',
]);

function sourcesUnder(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(full).isDirectory()) out.push(...sourcesUnder(full, rel));
    else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) out.push(rel);
  }
  return out;
}

describe('Artemis colour classes name real tokens', () => {
  const tokens = declaredTokens();

  it('parsed the theme', () => {
    // A parse that found nothing would make every check below vacuous.
    expect(tokens.size).toBeGreaterThan(20);
    for (const required of ['abyss', 'panel', 'inset', 'line', 'ink', 'beam']) {
      expect(tokens.has(required), `--color-${required} is missing from the theme`).toBe(true);
    }
  });

  const files = [
    ...sourcesUnder(join(ROOT, 'components'), 'components'),
    ...sourcesUnder(join(ROOT, 'lib'), 'lib'),
  ];

  it.each(files)('%s', (file) => {
    // Comments are stripped first: this file's own prose names the very token
    // it exists to catch, and a test that fails on its own documentation is a
    // test nobody keeps.
    const source = stripComments(readFileSync(join(ROOT, file), 'utf8'));
    const dead = new Set<string>();

    for (const [, name] of source.matchAll(USE)) {
      if (name === undefined) continue;
      // Strip an opacity modifier: `bg-panel/60` is still `panel`.
      const stripped = colourPart(name.split('/')[0]!);
      if (stripped === null) continue;
      const base = stripped;
      if (NOT_A_COLOUR.has(base)) continue;
      // Only judge names that look like ours. Anything else belongs to
      // Tailwind or shadcn and is not this test's business.
      if (!looksLikeOurs(base)) continue;
      if (!tokens.has(base)) dead.add(base);
    }

    expect(
      [...dead],
      `${file} uses a colour class whose token is not declared — Tailwind generates nothing for it, so the element silently has no colour.`,
    ).toEqual([]);
  });
});

/** Remove block and line comments, so prose about a class is not a use of it. */
function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/^\s*\/\/.*$/gm, ' ');
}

/**
 * Whether a class name is plausibly one of ours and therefore worth checking.
 *
 * Matching the known list exactly would only ever confirm what is already
 * declared and would never catch a typo — `bg-inste` would be waved through as
 * "not ours". So the rule is the shape of the mistake instead: a name close to
 * one of ours, or one of ours with something appended. That catches
 * `bg-surface`, `bg-inste` and `bg-panell` while leaving `bg-red-500` and
 * `text-muted-foreground` alone.
 */
function looksLikeOurs(name: string): boolean {
  if (ARTEMIS.test(name)) return true;
  // Tailwind's own scales are `word-number`; shadcn's are compound words with
  // `-foreground` or a known semantic root. Neither shape is ours.
  if (/-\d+$/.test(name)) return false;
  if (/foreground|background|primary|secondary|muted|destructive|popover|card|sidebar|chart|input|ring|border|accent/.test(name)) return false;
  if (/^(white|black|transparent|current|inherit|none|auto)$/.test(name)) return false;
  // A bare word that is not a Tailwind colour and not shadcn's: if it is within
  // one edit of one of ours, it is a typo; if it is a word we have never used,
  // it is a token someone assumed existed. `bg-surface` is the latter.
  return /^[a-z]+(-[a-z]+)*$/.test(name) && !TAILWIND_COLOURS.has(name);
}

/** Tailwind's palette roots, which are legitimate and not ours. */
const TAILWIND_COLOURS = new Set([
  'slate', 'gray', 'grey', 'zinc', 'neutral', 'stone', 'red', 'orange', 'yellow',
  'lime', 'green', 'emerald', 'teal', 'sky', 'blue', 'indigo', 'violet',
  'purple', 'fuchsia', 'pink', 'rose', 'cyan',
]);
