/**
 * Normalized token usage and cost.
 *
 * Providers report usage in their own vocabulary (the Claude Agent SDK uses
 * snake_case `input_tokens` / `cache_read_input_tokens` and a separate
 * `modelUsage` map). Adapters translate into these camelCase, provider-neutral
 * shapes so the UI has exactly one thing to render.
 */

/**
 * Token counts for a run, a turn or a single model.
 *
 * Every field is optional except {@link inputTokens} and {@link outputTokens}:
 * providers without prompt caching or server-side tools simply omit the rest.
 * Counts are absolute for the scope they describe, never percentages.
 */
export interface TokenUsage {
  /** Uncached input tokens billed at the full rate. */
  readonly inputTokens: number;
  /** Tokens generated by the model, including thinking tokens. */
  readonly outputTokens: number;
  /** Input tokens served from the prompt cache. */
  readonly cacheReadInputTokens?: number;
  /** Input tokens written into the prompt cache this turn. */
  readonly cacheCreationInputTokens?: number;
  /** Server-side tool invocations (e.g. web search) billed separately. */
  readonly webSearchRequests?: number;
}

/** Per-model usage, keyed by the provider's model identifier. */
export interface ModelTokenUsage extends TokenUsage {
  /** The model this row is for, as the provider names it. */
  readonly model: string;
  /** Cost attributable to this model, when the provider prices it. */
  readonly costUsd?: number;
  /** Total context window for this model, if reported. */
  readonly contextWindow?: number;
}

/**
 * How to interpret the numbers on a `usage` event.
 *
 * - `delta`      — usage incurred since the previous `usage` event.
 * - `cumulative` — running total for the whole run so far.
 * - `final`      — the authoritative total, emitted alongside `run.end`.
 *
 * Adapters must pick one convention per provider and stick to it. A UI that
 * sums `cumulative` events, or that replaces state on `delta` events, will
 * display nonsense — so the scope is on the wire rather than assumed.
 */
export type UsageScope = 'delta' | 'cumulative' | 'final';

/**
 * A usage snapshot.
 *
 * `contextTokens` / `contextWindow` describe how full the conversation's
 * context is right now, which is a different question from how many tokens
 * have been billed; both matter to the UI, so both are carried.
 */
export interface UsageSnapshot {
  readonly scope: UsageScope;
  readonly tokens: TokenUsage;
  /** Cost in US dollars, when the provider prices the request. */
  readonly costUsd?: number;
  /** Breakdown by model, when more than one model served the run. */
  readonly byModel?: readonly ModelTokenUsage[];
  /** Tokens currently occupying the context window. */
  readonly contextTokens?: number;
  /** Size of the context window the run is using. */
  readonly contextWindow?: number;
}

/* -------------------------------------------------------------------------- */
/* Plan usage — consumption against a subscription's limits                    */
/* -------------------------------------------------------------------------- */

/**
 * One rate-limit window.
 *
 * A percentage rather than a token count, because that is what the provider
 * publishes: plan limits are not a simple token budget, and inventing an
 * absolute number from a percentage would be a guess presented as a fact.
 */
export interface PlanUsageWindow {
  /** Stable identifier for the window, e.g. `five_hour`. */
  readonly id: PlanUsageWindowId;
  /** Human-readable name for the window, e.g. "5 hours". */
  readonly label: string;
  /** Share of the window consumed, 0–100. `null` when the provider omits it. */
  readonly utilization: number | null;
  /** When the window rolls over, ms since epoch. `null` when not reported. */
  readonly resetsAt: number | null;
}

/**
 * The windows a plan can be limited by.
 *
 * Open-ended on purpose: plans gain and lose windows, and an adapter that meets
 * an unfamiliar one should pass it through rather than drop it on the floor.
 */
export type PlanUsageWindowId =
  | 'five_hour'
  | 'seven_day'
  | 'seven_day_opus'
  | 'seven_day_sonnet'
  | 'seven_day_oauth_apps'
  | 'model_scoped'
  | 'extra_usage'
  | (string & {});

/**
 * A profile's consumption against its plan limits.
 *
 * Distinct from {@link UsageSnapshot}, which describes one run. This describes
 * the *account*: how much of the plan's capacity is gone and when it comes
 * back.
 *
 * `available: false` is a first-class, expected state rather than an error —
 * plan limits simply do not apply to API-key, Bedrock, Vertex or Foundry
 * billing, where usage is metered instead of capped. Callers should render the
 * `unavailableReason` rather than an empty meter, so the difference between
 * "nothing used" and "not applicable" is visible.
 */
export interface PlanUsage {
  readonly available: boolean;
  /** Why there is nothing to show. Present only when `available` is false. */
  readonly unavailableReason?: string;
  /** Plan tier as the provider names it, e.g. `pro`, `max`. */
  readonly subscriptionType?: string;
  /** Windows the plan is limited by, in display order. Empty when unavailable. */
  readonly windows: readonly PlanUsageWindow[];
  /** When this snapshot was taken, ms since epoch. Drives the staleness hint. */
  readonly fetchedAt: number;
}

/**
 * The most-consumed window, which is the one that will actually stop you.
 *
 * A plan with several windows is limited by whichever is closest to full, so a
 * single-glance indicator should show that one rather than an average — an
 * average of "5% of weekly, 98% of 5-hourly" reads as comfortable when you are
 * about to be cut off.
 */
export function bindingWindow(usage: PlanUsage | null | undefined): PlanUsageWindow | null {
  if (!usage?.available) return null;
  let worst: PlanUsageWindow | null = null;
  for (const window of usage.windows) {
    if (window.utilization === null) continue;
    if (worst === null || window.utilization > (worst.utilization ?? -1)) worst = window;
  }
  return worst;
}
