/**
 * Reading Claude's slash-command envelopes.
 *
 * When a user types `/model opus`, the CLI does not send that string to the
 * model. It runs the command itself and *narrates* it down the message stream
 * as a pair of ordinary user messages wrapped in its own markup:
 *
 *     <command-name>/model</command-name>
 *     <command-message>model</command-message>
 *     <command-args>opus[1m]</command-args>
 *
 *     <local-command-stdout>Set model to Fable 5 …</local-command-stdout>
 *
 * Nothing in the protocol says a user message may contain markup, so a consumer
 * that believes the stream renders both of those verbatim — which is exactly
 * what Artemis did: two chat bubbles full of XML for every `/effort`.
 *
 * This file is the one place that knows the shape. It answers "is this an
 * envelope, and what does it say", and the adapter turns that into a
 * `command.run` event. Everything here is a pure function over a string.
 *
 * ## What the real payloads look like
 *
 * Taken from stored transcripts rather than from the SDK types, which do not
 * describe this at all:
 *
 *  - **Tag order is not stable.** `/model` arrives name-first; a plugin command
 *    arrives message-first. So the tags are matched individually rather than
 *    with one whole-payload pattern.
 *  - **`<command-args>` is often present and empty** for a command that takes
 *    none, so "present" cannot mean "has arguments".
 *  - **Output carries ANSI.** `Set model to \x1b[1mFable 5\x1b[22m` — bold, as
 *    the CLI would draw it in a terminal. Rendered as-is in a GUI that is
 *    escape sequences on screen.
 *  - **The caveat is boilerplate.** A `<local-command-caveat>` message is the
 *    CLI telling the *model* to ignore what follows. It is addressed to the
 *    model, says nothing to a human, and is dropped.
 *  - **Plugin commands keep their namespace** — `/mattpocock-skills:implement`
 *    — and many of them print nothing at all, because they expand into a prompt
 *    instead of doing something locally.
 */

/** What a user message turned out to be. */
export type CommandEnvelope =
  | { readonly kind: 'invocation'; readonly name: string; readonly args?: string }
  | { readonly kind: 'output'; readonly text: string; readonly failed: boolean }
  | { readonly kind: 'caveat' };

/**
 * Strip ANSI escape sequences.
 *
 * The CLI writes for a terminal and Artemis is not one. Only the sequences that
 * actually appear in this payload are targeted — CSI (colour, bold, cursor) and
 * OSC (window title, hyperlinks) — rather than anything claiming to be a
 * general de-ANSI, which this is not.
 *
 * OSC first: its payload can itself contain characters that look like the start
 * of a CSI sequence, so removing CSI first would cut an OSC string in half and
 * leave its terminator behind as text.
 */
export function stripAnsi(text: string): string {
  return text.replace(OSC_SEQUENCE, '').replace(CSI_SEQUENCE, '');
}

/**
 * Operating System Command: `ESC ] \u2026 BEL` or `ESC ] \u2026 ESC \\`.
 *
 * Written with `\u` escapes rather than literal control characters, so the
 * pattern survives being read, copied and diffed rather than becoming an
 * invisible byte somebody deletes by accident.
 */
const OSC_SEQUENCE = /\u001B\][\s\S]*?(?:\u0007|\u001B\\)/g;

/** Control Sequence Introducer: `ESC [ \u2026 final byte`. Colour, bold, cursor. */
const CSI_SEQUENCE = /\u001B\[[0-9;?]*[ -/]*[@-~]/g;

/**
 * The contents of one tag, or `undefined` when it is absent.
 *
 * Non-greedy and dot-all: the body may contain newlines (a command's arguments
 * are frequently a whole paragraph — see the plugin commands, which take the
 * user's entire request as an argument), and a greedy match would swallow every
 * sibling tag up to the last closing bracket in the payload.
 *
 * Deliberately *not* a real XML parse. This is a fixed set of flat tags
 * generated by one program, and the bodies are user text that may well contain
 * `<` and `&` unescaped — which is to say it is not XML and would not survive a
 * parser that insisted it was.
 */
function tagBody(text: string, tag: string): string | undefined {
  const match = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`).exec(text);
  return match?.[1];
}

/**
 * Classify a user message, or `null` when it is ordinary prose.
 *
 * `null` is the overwhelmingly common answer and the one that must stay cheap:
 * this runs on every user message, so it checks for a `<` before doing anything
 * a regular expression would have to back-track through.
 */
export function parseCommandEnvelope(text: string): CommandEnvelope | null {
  // Envelopes are the whole message, but stored transcripts show leading
  // indentation on continuation lines, so trim rather than test position 0.
  const trimmed = text.trim();
  if (!trimmed.startsWith('<')) return null;

  if (trimmed.startsWith('<local-command-caveat>')) return { kind: 'caveat' };

  const stdout = tagBody(trimmed, 'local-command-stdout');
  if (stdout !== undefined) {
    return { kind: 'output', text: stripAnsi(stdout).trim(), failed: false };
  }
  const stderr = tagBody(trimmed, 'local-command-stderr');
  if (stderr !== undefined) {
    return { kind: 'output', text: stripAnsi(stderr).trim(), failed: true };
  }

  /*
   * `<command-name>` is the identity, and `<command-message>` is a label the
   * CLI shows while the command runs — the same string without its slash, in
   * every payload observed. The name is preferred and the message is a
   * fallback, so a payload carrying only the label still yields a command
   * rather than nothing.
   */
  const rawName = tagBody(trimmed, 'command-name') ?? tagBody(trimmed, 'command-message');
  if (rawName === undefined) return null;

  const name = stripAnsi(rawName).trim().replace(/^\/+/, '');
  // A nameless invocation is not one. Better to leave the message as prose
  // than to draw a chip for a command nobody can identify.
  if (name === '') return null;

  // Present-and-empty is the ordinary shape for a command that takes no
  // arguments, so emptiness is absence rather than an empty argument string.
  const args = stripAnsi(tagBody(trimmed, 'command-args') ?? '').trim();

  return { kind: 'invocation', name, ...(args === '' ? {} : { args }) };
}
